// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOCVUpiBeZOc64QvCX4cN-5oVDinvtdYM',
    appId: '1:585063965882:web:79e848a11406470dbf0e83',
    messagingSenderId: '585063965882',
    projectId: 'chatapp-52172',
    authDomain: 'chatapp-52172.firebaseapp.com',
    storageBucket: 'chatapp-52172.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClRI78hdAS6YVZ95M4GPzC3Wl-rwBjzjs',
    appId: '1:585063965882:android:7d6458dbd5153975bf0e83',
    messagingSenderId: '585063965882',
    projectId: 'chatapp-52172',
    storageBucket: 'chatapp-52172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbKlNAi97qaJ4R4SVstTGpTEep_E23Ko0',
    appId: '1:585063965882:ios:297be8d19ce2e518bf0e83',
    messagingSenderId: '585063965882',
    projectId: 'chatapp-52172',
    storageBucket: 'chatapp-52172.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbKlNAi97qaJ4R4SVstTGpTEep_E23Ko0',
    appId: '1:585063965882:ios:297be8d19ce2e518bf0e83',
    messagingSenderId: '585063965882',
    projectId: 'chatapp-52172',
    storageBucket: 'chatapp-52172.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOCVUpiBeZOc64QvCX4cN-5oVDinvtdYM',
    appId: '1:585063965882:web:da27c75195af0c31bf0e83',
    messagingSenderId: '585063965882',
    projectId: 'chatapp-52172',
    authDomain: 'chatapp-52172.firebaseapp.com',
    storageBucket: 'chatapp-52172.appspot.com',
  );
}
